apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations: 
   github.com/project-slug: aleksanderdushku/devops_scania
  description: ${{ values.name }} running on docker container locally
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
